 services:
   prometheus:
     image: prom/prometheus
     volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml # Mount the prometheus.yml file
     ports:
       - "9090:9090" # Expose port 9090 for Prometheus

   grafana:
     image: grafana/grafana
     ports:
       - "3000:3000" # Expose port 3000 for Grafana

   alertmanager:
     image: prom/alertmanager
     volumes:
       - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml # Mount the alertmanager.yml file
     ports:
       - "9093:9093" # Expose port 9093 for Alertmanager